### ISSUE TITLE
Suppose I need to set proxy for multiple(plural) URLs

### ISSUE THREAD

**Issue by govarthananve** [garmeeh/local-cors-proxy#16]
Hi ,
I have try the below comment but I got the error
`lcp --proxyUrl https://www.google.co.in https://www.google.co.uk/ `

I got below error
```
(UNKNOWN_VALUE: Unknown value: https://www.google.co.uk
    at commandLineArgs (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\node_modules\command-line-args\dist\index.js:1342:21)
    at Object.<anonymous> (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\bin\lcp.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  value: 'https://www.google.co.uk'
})
```
I have tried with twice --proxyUrl

`lcp --proxyUrl https://www.google.co.in --proxyUrl https://www.google.co.uk`

```
ALREADY_SET: Singular option already set [proxyUrl=https://www.google.co.in]
    at Option._set (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\node_modules\command-line-args\dist\index.js:1173:21)
    at Option.set (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\node_modules\command-line-args\dist\index.js:1157:10)
    at commandLineArgs (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\node_modules\command-line-args\dist\index.js:1365:14)
    at Object.<anonymous> (C:\Users\gvenunathan\AppData\Roaming\npm\node_modules\local-cors-proxy\bin\lcp.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  value: null,
  optionName: 'proxyUrl'
}
```

Pls help on that to resolve

**Comment by glowkeeper** [comment]
I know I'm late to the party (and I'm loathed to make a suggestion without testing it), but my immediate thought was, "couldn't you just use two separate proxies with different ports?", i.e.

```
lcp --proxyUrl https://www.google.co.in --port 8010
lcp --proxyUrl https://www.google.co.uk/ --port 8011
```

...it's what I'd try, anyway ;)

**Comment by cedibb** [comment]
```
--proxyUrl https://
```
