### ISSUE TITLE
error when setting credentials to true from package.json

### ISSUE THREAD

**Issue by alpomb** [garmeeh/local-cors-proxy#23]
When running lcp locally from a script setting credentials to true throws and error (below)
```bash
> lcp --proxyUrl https://sub.domain.com
--port 8000 --credentials true --origin http://localhost:8080

UNKNOWN_VALUE: Unknown value: true
    at commandLineArgs (D:\repo\recipe-svelte\node_modules\command-line-args\dist\index.js:1369:21)
    at Object.<anonymous> (D:\repo\recipe-svelte\node_modules\local-cors-proxy\bin\lcp.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)       
    at Module.load (internal/modules/cjs/l    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as 
runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  value: 'true'
}
```

A work around for the moment is to set the default to true in the optionDefinitions variable in /bin/lcp.js. Obviously that's not a permanent solution.

**Comment by ratsey** [comment]
Having issues myself, but I believe your issue is that --credentials takes no value. Just use
```
lcp --proxyUrl https://sub.domain.com
--port 8000 --credentials --origin http://localhost:8080
```
